# -*- coding: utf-8 -*-
"""PYTHON 1 - Intro. Ciencia de Datos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZB45UbMnz_fyNql2bYvcv70zuWaIjFto

# Introducción a la Ciencia de Datos con Python
## Sesión 1

Acá vamos a ver variables, expresiones y demás.

* asdfasd
* asdasdas
"""

a = 5

a

print(a)

b = 5.0

type(a)

type(b)

a

print(a)

n = 10

n

type(n)

pi = 3.141592

pi

type(pi)

mensaje = "Hola curso de diplomado!"

mensaje

type(mensaje)

float_n = float(n)

type(float(n))

int(pi)

str_n = str(n)

str_n

n + 3

str_n + '3'

# jhdakfjaskhdfakdfg

# sasdf
# as asdf
# asdfasdf
# asdfasdf

'''
asdasdjfadf
asdfljkdhlasdf
asdfkljasdf
'''

"""
adlkadhflakdfa
sdfaldjflasdf
asdfalkdfa
"""

# Cálculo del intercepto en y de una recta
x = 3
m = 2
b = 3.5
y = (m*x) + b

y

3+2

5-2

4*6

7/4

7//4

7%4

2**10

1024**(1/2)

import math
math.sqrt(100)

nombre = input("Ingresa tu nombre:\n")

nombre

print("Tu nombre es",nombre)

True

False

fuma = False

hace_ejercicio = False

saludable = hace_ejercicio or not fuma

saludable

x = 4
y = 5

x == y

x = 10; y = 20; z = 30

z

x < y and z % 2 == 0

x % y == 0 or z < y

edad = int(input("Ingresa tu edad:"))

if(edad >= 18):
  print("Bienvenid@ al casino.")

  dinero = int(input("Ingresa tu $$$:"))
  
  if(dinero > 0):
    print("Multiplica tu dinero.")
  else:
    print("Suertes que le digo, consigue dinero.")
else:
  print("Ve a casa bebé.")
print("Buena suerte!")

edad = int(input("Ingresa tu edad:\n"))

if(edad < 18):
  print("menor de edad")
elif(edad >= 18 and edad < 65):
  print("adulto joven")
else:
  print("adulto mayor")

lista = [1,2,3,4,5,9,11,15]

lista

for numero in lista:
  print(numero*2)

list(range(5,20,2))

for vez in range(5):
  print("esta es la repetición",vez+1)

i = 1
while i < 6:
  print(i)
  i = i + 1

suma = 0
for i in [1,2,3]:
  suma = suma + i

suma

import pandas as pd

pelis = pd.read_csv("/content/movies.csv", index_col = "Title")

type(pelis)

pelis

pelis.loc["Avatar"]

pelis.iloc[0]

pelis.sort_values(by="Title", ascending=False)

